export const ROUTES = {
  HOME: '/',
  CLUSTER: '/cluster',
  PODS: '/pods',
  DEPLOYMENTS: '/deployments',
  DAEMONSETS: '/daemonsets',
  AI_CONFIG: '/config/ai',
  STATEFULSETS: '/statefulsets',
  POD: '/pods/:podName',
  DEPLOYMENT: '/deployments/:deploymentName',
  DAEMONSET: '/daemonsets/:daemonSetName',
  STATEFULSET: '/statefulsets/:statefulSetName',
  NODES: '/nodes',
  NODE: '/nodes/:nodeName',
  NODE_PODS: '/nodes/:nodeName/pods',
} as const;
