export const ROUTES = {
  HOME: '/',
  CLUSTER: '/cluster',
  PODS: '/pods',
  DEPLOYMENTS: '/deployments',
  DAEMONSETS: '/daemonsets',
  AI_CONFIG: '/config/ai',
  AI_CONFIG_ADD_NEW: '/config/ai?addnew=true',
  STATEFULSETS: '/statefulsets',
  JOBS: '/jobs',
  CRONJOBS: '/cronjobs',
  POD: '/pods/:podName',
  DEPLOYMENT: '/deployments/:deploymentName',
  DAEMONSET: '/daemonsets/:daemonSetName',
  STATEFULSET: '/statefulsets/:statefulSetName',
  JOB: '/jobs/:jobName',
  CRONJOB: '/cronjobs/:cronJobName',
  NODES: '/nodes',
  NODE: '/nodes/:nodeName',
  NODE_PODS: '/nodes/:nodeName/pods',
  CONFIGMAPS: '/configmaps',
  CONFIGMAP: '/configmaps/:configMapName',
  SECRETS: '/secrets',
  SECRET: '/secrets/:secretName',
} as const;
